from lpnlang import Place, Transition, Token
from .funcs import *

ptasks = Place("ptasks")
pstart = Place("pstart")
p4 = Place("p4")
p0 = Place("p0")
p1 = Place("p1")
p2 = Place("p2")
p3 = Place("p3")
p5 = Place("p5")
p6 = Place("p6")
pstall = Place("pstall")
p7 = Place("p7")
p8 = Place("p8")
p10 = Place("p10")
p20 = Place("p20")
p21 = Place("p21")
p22 = Place("p22")
pdone = Place("pdone")
pt2p = Place("pt2p")
pt3p = Place("pt3p")
pt4p = Place("pt4p")
pt2p_hold = Place("pt2p_hold")
pt3p_hold = Place("pt3p_hold")
pt4p_hold = Place("pt4p_hold")
pvarlatency = Place("pvarlatency")
